export const errorLookup = {
    "MalformedUUID": "Die Target-ID ist ungültig",
    "MalformedInt": "Ein Anfrage-Parameter ist ungültig",
    "MalformedTime": "Der Zeitpunkt wurde nicht korrekt übermittelt",
    "TargetNotFound": "Das Target konnte nicht gefunden werden",
    "TargetTitleTooLong": "Der Titel des Targets ist zu lang",
    "TargetDescriptionTooLong": "Die Beschreibung des Targets ist zu lang",
    "QuoteNotFound": "Der Spruch konnte nicht gefunden werden",
    "QuoteTextTooLong": "Der Spruch ist zu lang",
    "QuoteNotPartOfTarget": "Der Spruch gehört nicht zu dem Target",
    "NoRecordsCreated": "Es gibt noch keine Records, die gelöscht werden könnten",
    "RecordTooOld": "Der letzte Record ist zu alt, um ihn noch zu löschen",
    "UserCannotViewTarget": "Du darfst dieses Target nicht ansehen",
    "UserCannotSubmitRecords": "Du darfst keine Records bei diesem Target eintragen",
    "UserCannotEditTarget": "Du darfst dieses Target nicht bearbeiten",
    "UserIsNotOwner": "Das Target kann nur vom Inhaber gelöscht werden",
    "GuestUserNotFound": "Diese Person war nie Teil des Targets",
    "UserNotFound": "Die Person konnte nicht gefunden werden (Email falsch?)",
    "MissingBody": "Anfrage ungültig (MissingBody)",
    "TooManyBlankFields": "Es dürfen keine Felder leergelassen werden (TooManyBlankFields)",
    "CannotDeleteSelfFromTarget": "Du kannst dich nicht selbst von diesem Target löschen",
    "CannotDeleteTargetOwner": "Der Inhaber des Targets kann nicht gelöscht werden",
    "CannotAddOwnerAsGuest": "Der Inhaber des Targets kann nicht als Person hinzugefügt werden",
    "APIAccessDenied": "Interner API-Zugriffsfehler. Bitte Admin benachrichten",
    "InternalError": "Interner Server-Fehler. Bitte Admin benachrichtigen",
};